import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer";
import Weather from "./Components/Weather";
import Header from "./Components/Header";
import Navigation from "./Components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ENews",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Weather />
        <Navigation />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
