import { Inter } from "next/font/google";
import "./globals.css";
import { ArticleProvider } from "./context/ArticleContext";
import ClientLayout from "./ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ENews",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ArticleProvider>
          <ClientLayout>{children}</ClientLayout>
        </ArticleProvider>
      </body>
    </html>
  );
}
